name: Validate

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 0 * * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: integration
          # Until the integration is listed in https://github.com/home-assistant/brands
          ignore: brands
